### ISSUE TITLE
Inconsistent install instructions

### ISSUE THREAD

**Issue by garethr** [kenfdev/conftest-orb#31]
On https://circleci.com/orbs/registry/orb/kenfdev/conftest-orb#commands-install, the Orb Quickstart Guide shows

```yaml
orbs:
  conftest-orb: kenfdev/conftest-orb@0.0.9
```

While the Usage Examples show:

```yaml
orbs:
  conftest: kenfdev/conftest-orb@x.y
```

Note the different name `contfest-orb` vs `conftest`.  The later is cleaner I think.

**Comment by kenfdev** [comment]
Thanks for pointing this out! I'll fix this.

**Comment by kenfdev** [comment]
I've dug into this and found that it's difficult... It seems this Quickstart guide is automatically generated and the orbs name is pulled from the registry name in CircleCI.

I'll have to drop the registry and create a new orb to solve this issue which will be a pretty big impact 🤔

**Comment by garethr** [comment]
Ah, in which case I wouldn't worry. Both work. Thanks for checking.
